---
- name: Install Jenkins
  hosts: all
  become: yes
  tasks:

    - name: Install openjdk8
      yum:
        name:
          - wget
          - java-1.8.0-openjdk
    
    - name: Install openjdk8 devel
      yum:
        name:
          - wget
          - java-1.8.0-openjdk-devel
 
    - name: Download jenkins.repo
      get_url:
        url: https://pkg.jenkins.io/redhat/jenkins.repo
        dest: /etc/yum.repos.d/jenkins.repo
 
    - name: Import Jenkins Key
      rpm_key:
        state: present
        key: https://pkg.jenkins.io/redhat/jenkins.io.key
 
    - name: Install Jenkins
      yum:
        name: jenkins
        state: present
 
    - name: Start & Enable Jenkins
      systemd:
        name: jenkins
        state: started
        enabled: true
 
    - name: Sleep for 30 seconds and continue with play
      wait_for: timeout=30
 
    - name: Get init password Jenkins
      shell: cat /var/lib/jenkins/secrets/initialAdminPassword
      changed_when: false
      register: result
 
    - name: Print init password Jenkins
      debug:
        var: result.stdout

    - name: Allow Network Ports in Firewalld
      firewalld:
        port: 8080/tcp
        state: enabled
        permanent: yes
        immediate: yes
    
    - name: Creates var jenkins directory
      file:
        path: /var/jenkins/
        state: directory
        mode: 777

    - name: Config permissions
      shell: |
       ssh-keygen -t rsa -f ~/.ssh/id_rsa -N '' -C "Jenkins agent key" <<< y
       cat ~/.ssh/id_rsa.pub >> ~/.ssh/authorized_keys
       chmod 600 ~/.ssh/authorized_keys
       sudo echo '{{ ansible_user }} ALL=(ALL) NOPASSWD: ALL' | sudo EDITOR='tee -a' visudo
    
    - name: Install Git
      yum:
        name: git
        state: present
