---
- name: Install Utils
  hosts: all
  become: yes
  tasks:
    - name: Creating a repository file for Google Chrome for Linux.
      file:
        path: /etc/yum.repos.d/google-chrome.repo
        state: touch

    - name: Adding repository for Google Chrome for Linux.
      blockinfile:
        path: /etc/yum.repos.d/google-chrome.repo
        block: |
          [google-chrome]
          name=google-chrome
          baseurl=http://dl.google.com/linux/chrome/rpm/stable/x86_64
          enabled=1
          gpgcheck=1
          gpgkey=https://dl.google.com/linux/linux_signing_key.pub

    - name: Install Google Chrome
      yum:
        name: google-chrome-stable
        state: present

    - name: Add Microsoft Package Repository
      yum:
        name: https://packages.microsoft.com/config/centos/7/packages-microsoft-prod.rpm
        state: present

    - name: Install NET Core SDK 2.2
      yum:
        name: dotnet-sdk-2.2
        state: present
    
    - name: Install NET Core SDK 3.3
      yum:
        name: dotnet-sdk-3.1
        state: present
    
    - name: Install ASP.NET Core Runtime 3.3
      yum:
        name: aspnetcore-runtime-3.1
        state: present
    
    - name: Creates sonar-scanner-ms directory
      file:
        path: /opt/sonar-scanner-ms
        state: directory

    - name: Install SonarScanner MS
      unarchive:
        src: https://github.com/SonarSource/sonar-scanner-msbuild/releases/download/4.10.0.19059/sonar-scanner-msbuild-4.10.0.19059-netcoreapp2.0.zip
        dest: /opt/sonar-scanner-ms
        remote_src: yes

    - name: Config permissions SonarScanner MS
      shell: |
        chmod 777 -R /opt/sonar-scanner-ms/

    - name: Install SonarScanner
      unarchive:
        src: https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-4.4.0.2170-linux.zip
        dest: /opt/
        remote_src: yes
    
    - name: Move sonar-scanner folder
      command: mv /opt/sonar-scanner-4.4.0.2170-linux/ /opt/sonar-scanner/
    
    - name: Config permissions SonarScanner
      shell: |
       chmod 777 -R /opt/sonar-scanner/

    - name: Creates liquibase directory
      file:
        path: /opt/liquibase
        state: directory

    - name: Install Liquibase
      unarchive:
        src: https://github.com/liquibase/liquibase/releases/download/v3.10.1/liquibase-3.10.1.tar.gz
        dest: /opt/liquibase
        remote_src: yes
    
    - name: Download and install Docker Compose
      get_url:
        url: https://github.com/docker/compose/releases/download/1.21.2/docker-compose-Linux-x86_64
        dest: /usr/local/bin/docker-compose
        mode: 0755
    
